config/routes.rb
Rails.application.routes.draw do
  resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'board#index'

  get '/boards' => 'board#index'
  get '/boards/new' => 'board#new'
  post '/boards' => 'board#create'
  get '/boards/:id/edit' => 'board#edit'
  get '/boards/:id' => 'board#show'
  post '/boards/:id' => 'board#update'
  delete '/boards/:id' => 'board#destroy'

  get '/signin' => 'session#signin'
  post '/user_signin' => 'session#user_signin'
  get '/signup' => 'session#signup'
  post '/user_signup' => 'session#user_signup'
  delete '/logout' => 'session#logout'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def user_sign_in?
    redirect_to '/signin', notice: "로그인이 필요합니다." if session[:user_id].nil?
  end

  def current_user
    unless session[:user_id].nil?
      @current_user = User.find(session[:user_id])
    end
    @current_user
  end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  before_action :user_sign_in?, except: [:index, :show]

  def index
    @boards = Board.all
    puts current_user.inspect
  end

  def show
    @board = Board.find(params[:id])
  end

  def new

  end

  def create
    board = Board.create(user_id: current_user.id, title: params[:title], contents: params[:contents])
    redirect_to "/boards/#{board.id}", notice: "글 작성 완료!!"
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    board = Board.find(params[:id])
    board.update(title: params[:title], contents: params[:contents])
    redirect_to "/boards/#{board.id}", notice: "글 수정 완료!!!"
  end

  def destroy
    Board.find(params[:id]).destroy
    redirect_to '/', notice: "글 삭제 완료!!!"
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def signin
  end

  def user_signin
    user = User.find_by(email: params[:email])
    if user.nil?
      flash[:notice] = "없는 회원임ㅋㅋ"
      redirect_to '/signin'
    else
      if user.password_digest == params[:password]
        flash[:notice] = "로그인 성공!"
        session[:user_id] = user.id
        redirect_to '/'
      else
        flash[:notice] = "비밀번호 틀림ㅋㅋ"
        redirect_to '/signin'
      end
    end
  end

  def signup

  end

  def user_signup
    User.create(
      email: params[:email],
      password_digest: params[:password]
    )
    redirect_to '/signin', notice: "회원가입 완료!!"
  end

  def logout
    session.delete(:user_id)
    redirect_to '/', notice: "로그아웃 하셨습니다."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/board/edit.html.erb
<form action="/boards/<%= @board.id %>" method='post'>
  <input type="text" name='title' value="<%= @board.title %>"><br />
  <textarea name="contents" cols="30" rows="10"><%= @board.contents %></textarea><br>
  <input type="submit" value="수정하기">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/board/index.html.erb
<h1>Boards</h1>
<table class="table" id="t1">
  <thead>
    <tr>
      <th>글번호</th>
      <th>제목</th>
      <th>보기</th>
      <th>수정</th>
      <th>삭제</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |b| %>
    <tr class="boards" data-value="<%= b.id %>">
      <td><%= b.id %></td>
      <td><%= b.title %></td>
      <td><a href="/boards/<%= b.id %>">보기</a></td>
      <td><a href="/boards/<%= b.id %>/edit">수정</a></td>
      <td><a href="/boards/<%= b.id %>" data-method="delete" data-confirm="삭제할꼬얌?">삭제</a></td>
    </tr>
    <% end %>
  </tbody>
</table>
<a href="/boards/new">새글쓰기</a>

<script>
window.onload = function() {
  alert("done1");
  console.log(document.getElementsByTagName("table"));
  var boards = document.getElementsByClassName("boards");
  for(var i = 0; i < boards.length; i++) {
    boards[i].addEventListener('click', function() {
      var id = this.getAttribute('data-value');
      console.log(id);
      location.href = "/boards/" + id;
    }, false);
  }
}

alert("done2");

</script>

app/views/board/new.html.erb
<form action="/boards" method='post'>
  <input type="text" name='title'><br />
  <textarea name="contents" cols="30" rows="10"></textarea><br>
  <input type="submit" value="작성하기">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/board/show.html.erb
<h1><%= @board.title %></h1>
<p><%= @board.contents %></p>

<a href="/boards">홈으로</a>

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JavascriptClass</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <% if current_user %>
      <%= current_user.email %>님
      <a href="/logout" data-method="delete" data-confirm="로그아웃하시겠습니까?">로그아웃</a>
    <% else %>
      <a href="/signin">로그인</a>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/signin.html.erb
<h1>로그인</h1>
<form action="/user_signin" method="post">
  ID: <input type="email" name="email"><br>
  PW: <input type="password" name="password"><br>
  <input type="submit" value="로그인">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
</form>
<a href="/signup">회원가입</a>

app/views/session/signup.html.erb
<h1>회원가입</h1>
<form action="/user_signup" method="post">
  ID: <input type="email" name="email"><br>
  PW: <input type="password" name="password"><br>
  PW_Confirmation: <input type="password" name="password_confirmation"><br>
  <input type="submit" value="가입하기">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
</form>